within BESMod.Examples.TEASERExport;
package HighOrderArchetypeExample "TEASER's AixLib high order single family house, as reduced order and as high order model"
  extends Modelica.Icons.Package;

  annotation (Documentation(info="<html>
<p>
  The single family house of AixLib's high order model (HOM), generated by
  TEASER's archetype <code>AixLibHighOrderSingleFamilyHouse</code> for a building
  of 1984 with 170 m&sup2; and exported with <code>export_with_hom=True</code>.
  Every example therefore comes twice, with the same energy system:
</p>
<ul>
  <li>without suffix, the building as TEASER's single zone reduced order model
  (<a href=\"modelica://BESMod.Systems.Demand.Building.TEASERThermalSingleZone\">TEASERThermalSingleZone</a>),
  with the user profiles of the ten rooms merged into its one zone by
  <a href=\"modelica://BESMod.Systems.UserProfiles.TEASERHOMtoROM\">TEASERHOMtoROM</a></li>
  <li>with the suffix <code>_HOM</code>, the same building as AixLib's high order model
  (<a href=\"modelica://BESMod.Systems.Demand.Building.AixLibHighOrder\">AixLibHighOrder</a>)
  with its ten heated rooms and the user profiles room by room
  (<a href=\"modelica://BESMod.Systems.UserProfiles.AixLibHighOrderProfiles\">AixLibHighOrderProfiles</a>)</li>
</ul>
<p>
  The walls, windows and surface orientations of the HOM are TEASER's own records in
  <code>SingleFamilyHouse_DataBase</code>, so both models are built from the same construction data,
  and both are sized from the same room-wise heat loads. Compared to the export, the weather is
  BESMod's default (TRY2015 Potsdam, which TEASER was given for the heat loads) and the internal
  gains are reduced to the one day they repeat
  (<code>modelica://BESMod/Resources/InternalGainsHighOrderArchetypeExample.txt</code>).
</p>
<p>
  TEASER's example <code>e14_compare_hom_and_rom.py</code> compares the two models, and
  TEASER's script <code>scripts/update_besmod_hom_example.py</code> regenerates this package.
</p>
</html>"));
end HighOrderArchetypeExample;
