# Variables
# image_name : registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:Dymola_2022-miniconda
# ci_stage_style_check : Style_check
# modelicapyci_syntax_naming_guideline : ModelicaPyCI.syntax.naming_guideline
# library : BESMod
# ci_naming_guideline : ci_check_naming
# result_dir : ci-tests/result
# arg : --changed-flag  --gitlab-page https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/BESMod --github-token ${GITHUB_API_TOKEN} --working-branch $CI_COMMIT_BRANCH --github-repository RWTH-EBC/BESMod --main-branch main --config ci-tests/naming_guideline.toml --library BESMod 

include: 'ci-tests/scripts/utilities.yml'
stages:
    - Style_check


NamingGuideline:BESMod:PR:
    image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:Dymola_2022-miniconda
    stage: Style_check
    before_script:
        - !reference [.activate_python_and_install_requirements, script]
    script:
        - python -m ModelicaPyCI.syntax.naming_guideline --changed-flag  --gitlab-page https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/BESMod --github-token ${GITHUB_API_TOKEN} --working-branch $CI_COMMIT_BRANCH --github-repository RWTH-EBC/BESMod --main-branch main --config ci-tests/naming_guideline.toml --library BESMod 
    artifacts:
        paths:
            - ci-tests/result/
        expire_in: 7 day
    rules:
        - if: $CI_COMMIT_MESSAGE  =~ /ci_check_naming/ && $CI_PIPELINE_SOURCE == "push"
          when: always
        - !reference [.rules:PR , rules]

