# Variables
# image_name : registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:Dymola2024xRefresh1-micromamba-alternative
# ci_stage_style_check : Style_check
# modelicapyci_syntax_naming_guideline : ModelicaPyCI.syntax.naming_guideline
# library : BESMod
# ci_naming_guideline : ci_check_naming
# result_dir : ci-tests/result
# arg : --changed-flag  --main-branch main --config ci-tests/naming_guideline.toml --library BESMod 

include: 'ci-tests/scripts/utilities.yml'
stages:
    - Style_check


NamingGuideline:BESMod:push:
    image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:Dymola2024xRefresh1-micromamba-alternative
    stage: Style_check
    before_script:
        - !reference [.activate_python_and_install_requirements, script]
    script:
        - python -m ModelicaPyCI.syntax.naming_guideline --changed-flag  --main-branch main --config ci-tests/naming_guideline.toml --library BESMod 
    artifacts:
        paths:
            - ci-tests/result/
        expire_in: 7 day
    rules:
        - if: $CI_COMMIT_MESSAGE  =~ /ci_check_naming/ && $CI_PIPELINE_SOURCE == "push"
          when: always
        - !reference [.rules:push , rules]

