# You can adjust the sequence of the stages to your needs:
stages:
    - Ref_Check
    - open_PR
    - create_html_whitelist
    - create_model_whitelist
    - create_example_whitelist
    - HTML_Check
    - Style_check
    - model_check
    - OM_model_check
    - simulate
    - OM_simulate
    - RegressionTest
    - plot_ref
    - prepare
    - prepare_pages
    - deploy

variables:
    Github_Repository: RWTH-EBC/BESMod
    GITLAB_Page:  https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/BESMod

include:
    - 'ci-tests/scripts/syntax_tests/style_check.gitlab-ci.yml'  
    - 'ci-tests/scripts/unit_tests/simulate_OM_model.gitlab-ci.yml'  
    - 'ci-tests/scripts/deploy/prepare_pages.gitlab-ci.yml'  
    - 'ci-tests/scripts/unit_tests/check_model.gitlab-ci.yml'  
    - 'ci-tests/scripts/unit_tests/regression_test.gitlab-ci.yml'  
    - 'ci-tests/scripts/unit_tests/check_OM_model.gitlab-ci.yml'  
    - 'ci-tests/scripts/syntax_tests/html_check.gitlab-ci.yml'  
    - 'ci-tests/scripts/syntax_tests/naming_guideline.gitlab-ci.yml'  
    - 'ci-tests/scripts/unit_tests/simulate_model.gitlab-ci.yml'  
    - project: 'EBC/EBC_all/gitlab_ci/templates'
      file: 'pages/gl-pages.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
      file: 'pages/gh-pages.gitlab-ci.yml'
