within BESMod.Examples;
package TEASERExport "Example of a building exported with TEASER."
extends Modelica.Icons.ExamplesPackage;

  annotation (Documentation(info="<html>
<p>
  <a href=\"https://github.com/RWTH-EBC/TEASER\">TEASER</a> (Tool for Energy Analysis and Simulation for Efficient Retrofit) 
  provides a streamlined approach to generating archetype buildings with minimal input requirements. 
  These buildings can be exported to BESMod as <a href=\"BESMod.Systems.Demand.Building.TEASERThermalZone\">
  BESMod.Systems.Demand.Building.TEASERThermalZone</a> models and integrated into energy system simulations.
</p>

<p>
  This example showcases part of the exported package generated by the TEASER script 
  <code>e11_export_besmod_model.py</code>, featuring a single building. The export includes:
</p>
<ul>
  <li>The building's model with its zone records</li>
  <li>Three optional example energy systems, where the building is automatically integrated, creating ready-to-run models</li>
</ul>

<p>
  <a href=\"modelica://BESMod.Examples.TEASERExport.HighOrderArchetypeExample\">HighOrderArchetypeExample</a>
  is TEASER's archetype of AixLib's high order single family house, exported with
  <code>export_with_hom=True</code>. Each of its examples comes twice, with the building as
  <a href=\"modelica://BESMod.Systems.Demand.Building.TEASERThermalSingleZone\">TEASERThermalSingleZone</a>
  and as the high order model
  <a href=\"modelica://BESMod.Systems.Demand.Building.AixLibHighOrder\">AixLibHighOrder</a>
  (suffix <code>_HOM</code>) in the same energy system.
</p>

<p>
  For additional details on using TEASER, please refer to its <a href=\"https://github.com/RWTH-EBC/TEASER\">official documentation</a>.
</p>

<p>
  In this BESMod example and for regression testing, resources such as weather data, internal gains, and 
  <code>.mos</code> scripts have been adjusted to ensure compatibility.
</p>
</html>
"));
end TEASERExport;
