# ci_stage_OM_model_check: OM_model_check
# library: BESMod
# ci_OM_check_commit: ci_om_check
# OM_Image: registry.git.rwth-aachen.de/ebc/ebc_intern/openmodelica-docker:main
# OM_python_check_model_module: ModelicaPyCI.unittest.om_check
# result_dir: ci-tests/result
# expire_in_time: 7h
# arg_push: --om-options OM_CHECK --startup-mos startup.mos --whitelist-library IBPSA --packages $lib_package --library BESMod 
# arg_changed: --om-options OM_CHECK --startup-mos startup.mos --changed-flag  --whitelist-library IBPSA --packages $lib_package --library BESMod 
# packages_per_job: {'Examples': 'Examples', 'Systems': 'Systems', 'Other': 'Tutorial Utilities'}

include: 'ci-tests/scripts/utilities.yml'

stages:
    - OM_model_check


.OM_check_model_job:push:
    image: registry.git.rwth-aachen.de/ebc/ebc_intern/openmodelica-docker:main
    stage: OM_model_check
    before_script:
        - !reference [.activate_python_and_install_requirements, script]
        - !reference [.custom_install_additional_modelica_libraries, script]
        - !reference [.open_modelica_git_user_setting, script]
    script:
        - runuser -u openmodelicausers -- python3 -m ModelicaPyCI.unittest.om_check --om-options OM_CHECK --startup-mos startup.mos --whitelist-library IBPSA --packages $lib_package --library BESMod 
    artifacts:
        when: on_failure
        paths:
            - ci-tests/result/
        expire_in: 7h
    allow_failure: true
    rules:
        - if: $CI_COMMIT_MESSAGE  =~ /ci_om_check/ && $CI_PIPELINE_SOURCE == "push"
          when: always
        - !reference [.rules:push , rules]

.OM_check_model_job:changed:
    image: registry.git.rwth-aachen.de/ebc/ebc_intern/openmodelica-docker:main
    stage: OM_model_check
    before_script:
        - !reference [.activate_python_and_install_requirements, script]
        - !reference [.custom_install_additional_modelica_libraries, script]
        - !reference [.open_modelica_git_user_setting, script]
    script:
        - runuser -u openmodelicausers -- python3 -m ModelicaPyCI.unittest.om_check --om-options OM_CHECK --startup-mos startup.mos --changed-flag  --whitelist-library IBPSA --packages $lib_package --library BESMod 
    artifacts:
        when: on_failure
        paths:
            - ci-tests/result/
        expire_in: 7h
    allow_failure: true
    rules:
        - !reference [.rules:changed, rules]

OM_Check_BESMod_Examples:push:
    variables:
        lib_package: Examples
    extends: .OM_check_model_job:push

OM_Check_BESMod_Systems:push:
    variables:
        lib_package: Systems
    extends: .OM_check_model_job:push

OM_Check_BESMod_Other:push:
    variables:
        lib_package: Tutorial Utilities
    extends: .OM_check_model_job:push


OM_Check_BESMod_Examples:changed:
    variables:
        lib_package: Examples
    extends: .OM_check_model_job:changed

OM_Check_BESMod_Systems:changed:
    variables:
        lib_package: Systems
    extends: .OM_check_model_job:changed

OM_Check_BESMod_Other:changed:
    variables:
        lib_package: Tutorial Utilities
    extends: .OM_check_model_job:changed

