# dym_image_name : registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:Dymola_2022-miniconda
# ci_stage_simulate: simulate
# ci_stage_create_exampel_whitelist: create_example_whitelist
# arg_push : --dym-options DYM_SIM --filter-whitelist-flag  --changed-flag  --dymola-version 2022 --additional-libraries-to-load  --packages $lib_package --library BESMod 
# arg_PR: --dym-options DYM_SIM --filter-whitelist-flag  --dymola-version 2022 --additional-libraries-to-load  --packages $lib_package --library BESMod 
# library: BESMod
# ci_check_commit ci_simulate
# modelicapyci_test_validate_module: ModelicaPyCI.unittest.checkpackages.validatetest
# package_list: ['Examples', 'Tutorial', 'Utilities', 'Systems']
# arg_wh: --dym-options DYM_SIM --create-whitelist-flag  --dymola-version 2022 --additional-libraries-to-load  --packages Examples Tutorial Utilities Systems --library BESMod 
# bot_update_model_whitelist_commit: CI message from ebc-aixlib-bot. Update file whitelist-simulate_file. Please pull the new files before push again.
# whitelist_model_file: dymola_simulate_whitelist.txt
# ci_create_model_whitelist_commit: ci_create_example_whitelist
# result_dir : ci-tests/result
# expire_in_time: 7h
# xvfb_flag : xvfb-run -n 77
# config_ci_exit_file : exit.sh

include: 'ci-tests/scripts/utilities.yml'

stages:
    - simulate
    - create_example_whitelist


.simulate_model_job:PR:
    image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:Dymola_2022-miniconda
    stage: simulate
    before_script:
        - !reference [.activate_python_and_install_requirements, script]
        - !reference [.custom_install_additional_modelica_libraries, script]
    script:
        - xvfb-run -n 77 python -m ModelicaPyCI.unittest.checkpackages.validatetest  --dym-options DYM_SIM --filter-whitelist-flag  --dymola-version 2022 --additional-libraries-to-load  --packages $lib_package --library BESMod 
    artifacts:
        when: on_failure
        paths:
            - ci-tests/result/
        expire_in: 7h
    rules:
        - if: $CI_COMMIT_MESSAGE  =~ /ci_simulate/ && $CI_PIPELINE_SOURCE == "push"
          when: always
        - !reference [.rules:PR , rules]

.simulate_model_job:Push:
    image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:Dymola_2022-miniconda
    stage: simulate
    before_script:
        - !reference [.activate_python_and_install_requirements, script]
        - !reference [.custom_install_additional_modelica_libraries, script]
    script:
        - xvfb-run -n 77 python -m ModelicaPyCI.unittest.checkpackages.validatetest --dym-options DYM_SIM --filter-whitelist-flag  --changed-flag  --dymola-version 2022 --additional-libraries-to-load  --packages $lib_package --library BESMod 
    artifacts:
        when: on_failure
        paths:
            - ci-tests/result/
        expire_in: 7h
    rules:
        - !reference [.rules:push , rules]

Simulate_BESMod_Examples:PR:
    variables:
        lib_package: Examples
    extends: .simulate_model_job:PR

Simulate_BESMod_Tutorial:PR:
    variables:
        lib_package: Tutorial
    extends: .simulate_model_job:PR

Simulate_BESMod_Utilities:PR:
    variables:
        lib_package: Utilities
    extends: .simulate_model_job:PR

Simulate_BESMod_Systems:PR:
    variables:
        lib_package: Systems
    extends: .simulate_model_job:PR



Simulate_BESMod_Examples:Push:
    variables:
        lib_package: Examples
    extends: .simulate_model_job:Push

Simulate_BESMod_Tutorial:Push:
    variables:
        lib_package: Tutorial
    extends: .simulate_model_job:Push

Simulate_BESMod_Utilities:Push:
    variables:
        lib_package: Utilities
    extends: .simulate_model_job:Push

Simulate_BESMod_Systems:Push:
    variables:
        lib_package: Systems
    extends: .simulate_model_job:Push


simulate_whitelist_job:
    image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:Dymola_2022-miniconda
    stage:  create_example_whitelist
    before_script:
        - !reference [.activate_python_and_install_requirements, script]
        - !reference [.custom_install_additional_modelica_libraries, script]
        - !reference [.github_ssh_auth, script]
    script:
        - mkdir whitelist && cd whitelist
        - git clone --single-branch --branch $CI_COMMIT_REF_NAME git@github.com:$Github_Repository.git
        - cd $CI_PROJECT_NAME
        - xvfb-run -n 77 python -m ModelicaPyCI.unittest.checkpackages.validatetest  --dym-options DYM_SIM --create-whitelist-flag  --dymola-version 2022 --additional-libraries-to-load  --packages Examples Tutorial Utilities Systems --library BESMod 
    after_script:
        - cd whitelist && cd $CI_PROJECT_NAME
        - if cat exit.sh | grep "FAIL"; then
            message="CI message from ebc-aixlib-bot. Update file whitelist-simulate_file. Please pull the new files before push again." ;
            git add dymola_simulate_whitelist.txt ;
            git commit -m "$message" ;
            git push git@github.com:$Github_Repository.git ;
            exit 0;
          else
            exit 0 ;
          fi
    artifacts:
        paths:
            - ci-tests/result/
        expire_in: 7h
    rules:
        - if: $CI_COMMIT_MESSAGE =~ /ci_create_example_whitelist/ && $CI_PIPELINE_SOURCE == "push"
          when: always
